# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/sysctl
  block:

    - name: CIS | Ensure suid programs can't dump core
      become: true
      ansible.builtin.template:
        src: 'etc/sysctl.d/60-fs_suid_dumpable.conf.j2'
        dest: '/etc/sysctl.d/60-fs_suid_dumpable.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: CIS | Ensure core dumps are restricted
      become: true
      ansible.builtin.template:
        src: 'etc/security/limits.d/60-restrict-core-dumps.conf.j2'
        dest: '/etc/security/limits.d/60-restrict-core-dumps.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_limits'
